### ISSUE TITLE
App no longer works on iOS 9.3 (iPhone 5)

### ISSUE THREAD

**Issue by 153957** [jefferyleo/f.lux#22]
I have not tried to load it again from XCode, but after the update the installed version no longer works. It does seem to launch, but the iPhone jumps back to the homescreen. f.lux does show up in the app switcher, but switching to it makes it jump back to the homescreen. So the app seems to have launched, but it has no effect.

Apple probably broke it intentionally when implementing its Night Shift, 'unfortunately' that is not supported on the iPhone 5.

**Comment by greatquux** [comment]
I actually had the same exactly problem with another "side-loaded" app I use on my iPhone 5, the https://github.com/rickyzhang82/tethering app. I just updated my Mac to the latest OS X and Xcode and recompiled and reinstalled and now it works fine, so I hope the same thing will work for you with f.lux.  It works on my iPhone 5 just great.  I was actually waiting for Night Shift and I only installed f.lux once I saw that Night Shift wasn't going to be supported on 32-bit iOS... what's up with that?! I guess they are doing it in a more processor-intensive way than f.lux, since Night Shift also doesn't work in Low Power Mode.

**Comment by greatquux** [comment]
Also take a look at https://forum.justgetflux.com/topic/2198/sideload-f-lux-stops-working-when-provisioning-profile-expires/2 -- it seems that the free Developer accounts expire after 3 months, as opposed to the ones you pay for which are at least 1 year.  (I knew there had to be a catch there somewhere!)  Friggin' Apple.

**Comment by 153957** [comment]
Thanks for the pointers! Unfortunately I won't be able to try it soon, because Im still running Yosemite, and the new XCode (7.3) for iOS 9.3 requires El Capitan.

**Comment by michaelybecker** [comment]
Can confirm this method works on 9.3.1 - did it just now, took about 5 minutes. Thanks to everyone in this thread and of course to @jefferyleo! (And damn you and your greedy business practices, Apple - if you'd only made Night Shift available on older devices I wouldn't be incentivized to sidestep your terms...)

**Comment by greatquux** [comment]
Unfortunately I had to stop using it because f.lux is not restoring my color in the morning. :(
